flowchart TD
    A["Usuário CLI"] -->|"Argumentos"| B["Função Principal"]
    B --> C{"Validação dos Critérios"}
    C -- "Critérios válidos" --> D["Gerador de Senha"]
    C -- "Critérios inválidos" --> H["Mensagem de erro amigável"]
    D --> E["Exibir Senha"]
    E --> F["Saída no Terminal"]
    E --> G["Copia para área de transferência"]
    H --> F
    %% Critérios detalhados
    C -.-> D1["Maiúsculas"]
    C -.-> D2["Minúsculas"]
    C -.-> D3["Números"]
    C -.-> D4["Especiais"]
    style F fill:#fef9c3,stroke:#a16207
    style G fill:#fca5a5,stroke:#b91c1c
